FROM intel/intel-extension-for-pytorch:2.3.0-xpu

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    HF_HOME=/data/huggingface

WORKDIR /app

COPY remote_server /app/remote_server
COPY docker/requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r /app/requirements.txt

EXPOSE 8008

WORKDIR /app/remote_server

# XPU 环境下不建议 4bit，直接用非 NF4 版本
CMD ["python", "remote_text_encoder_server.py"]
